export const AppErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_URL: 'INVALID_URL',
  SCRAPE_FAILED: 'SCRAPE_FAILED',
  CLIENT_DELETE_FAILED: 'CLIENT_DELETE_FAILED',
  UPDATE_FAILED: 'UPDATE_FAILED',

  AUTH_MISSING_TOKEN: 'AUTH_MISSING_TOKEN',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCESS_DENIED: 'ACCESS_DENIED',
  EMAIL_IN_USE: 'EMAIL_IN_USE',
  SLUG_IN_USE: 'SLUG_IN_USE',
  ORIGIN_NOT_ALLOWED: 'ORIGIN_NOT_ALLOWED',
} as const;

export type AppErrorCode = (typeof AppErrorCode)[keyof typeof AppErrorCode];
