export const mockData = [
    {
        "name": "גר.ליקס מיני",
        "enName": "Gar.Lix Mini",
        "isNew": false,
        "rating": "(0)",
        "deal": "3 ב-₪279",
        "marketer": "טוגדר",
        "manufacturer": "קנאדו",
        "brand": "קנאדו",
        "expiry": "09/26",
        "price": "₪99",
        "catalogPrice": "₪299",
        "parent1": "גרליק ברת' 2.0",
        "parent2": "דיזיינר ראנטז",
        "originStrain": "גלייזד גרליק",
        "countryOfOrigin": "ישראל",
        "terpenes": "",
        "packageType": "שקית"
    },
    {
        "name": "ראיין",
        "enName": "Rhine",
        "isNew": true,
        "rating": "(0)",
        "deal": "3 ב-₪279",
        "marketer": "קנטק",
        "manufacturer": "קנאפארמה",
        "brand": "לומה",
        "expiry": "12/26",
        "price": "₪99",
        "catalogPrice": "₪199",
        "parent1": "סקאנק #1",
        "parent2": "אפגני ",
        "originStrain": "אוג'י צ'יז",
        "countryOfOrigin": "קנדה",
        "terpenes": "",
        "packageType": "שקית"
    },
    {
        "name": "ואנקה",
        "enName": "Wanaka",
        "isNew": false,
        "rating": "(9) 4.4",
        "deal": "3 ב-₪299",
        "marketer": "קנפוקס",
        "manufacturer": "קנערבה",
        "brand": "טא-מוקו",
        "expiry": "11/27",
        "price": "₪109",
        "catalogPrice": "₪199",
        "parent1": "פלורידה אוג'י  ",
        "parent2": "אפגני ",
        "originStrain": "ספאייר אוג'י",
        "countryOfOrigin": "ישראל",
        "terpenes": "",
        "packageType": "צנצנת"
    },
    {
        "name": "ראנגי",
        "enName": "Rangi",
        "isNew": false,
        "rating": "(1) 4",
        "deal": "3 ב-₪299",
        "marketer": "קנפוקס",
        "manufacturer": "קנערבה",
        "brand": "טא-מוקו",
        "expiry": "11/27",
        "price": "₪109",
        "catalogPrice": "₪199",
        "parent1": "סטארדוג גויאבה",
        "parent2": "אוג'י קוש  ",
        "originStrain": "",
        "countryOfOrigin": "ישראל",
        "terpenes": "",
        "packageType": "צנצנת"
    },
    {
        "name": "אור ג'י.בי סמול",
        "enName": "Or G.B Small",
        "isNew": false,
        "rating": "(2) 3.5",
        "deal": "",
        "marketer": "טוגדר",
        "manufacturer": "",
        "brand": "טוגדר",
        "expiry": "01/27",
        "price": "₪129",
        "catalogPrice": "₪199",
        "parent1": "גלוברי",
        "parent2": "אוג'י קוש  ",
        "originStrain": "גלוברי או ג'י",
        "countryOfOrigin": "ישראל",
        "terpenes": "",
        "packageType": "שקית"
    },
    {
        "name": "אר.אס.סי",
        "enName": "R.S.C",
        "isNew": false,
        "rating": "(1) 3",
        "deal": "",
        "marketer": "טוגדר",
        "manufacturer": "קנאדו",
        "brand": "קנאדו",
        "expiry": "12/26",
        "price": "₪129",
        "catalogPrice": "₪399",
        "parent1": "ריינבו שרבט",
        "parent2": "קאפ ג'אנקי",
        "originStrain": "",
        "countryOfOrigin": "ישראל",
        "terpenes": "",
        "packageType": "שקית"
    },
    {
        "name": "גר.ליקס",
        "enName": "Gar.Lix",
        "isNew": false,
        "rating": "(1) 3",
        "deal": "",
        "marketer": "טוגדר",
        "manufacturer": "קנאדו",
        "brand": "קנאדו",
        "expiry": "07/26",
        "price": "₪129",
        "catalogPrice": "₪349",
        "parent1": "גרליק ברת' 2.0",
        "parent2": "דיזיינר ראנטז",
        "originStrain": "גלייזד גרליק",
        "countryOfOrigin": "ישראל",
        "terpenes": "",
        "packageType": "שקית"
    },
    {
        "name": "סלאק מיני",
        "enName": "Slac Mini",
        "isNew": true,
        "rating": "(0)",
        "deal": "",
        "marketer": "טוגדר",
        "manufacturer": "",
        "brand": "טוגדר",
        "expiry": "03/27",
        "price": "₪129",
        "catalogPrice": "₪329",
        "parent1": "אוג'י קוש ברת'",
        "parent2": "גויאבה ג'לאטו",
        "originStrain": "קריביאן קוקיז",
        "countryOfOrigin": "ישראל",
        "terpenes": "לינאלול, קריופילן, מירצן, לימונן, פיינן",
        "packageType": "שקית"
    },
    {
        "name": "דאבליו.אם.זד סמול",
        "enName": "W.M.Z Small",
        "isNew": true,
        "rating": "(2) 4",
        "deal": "",
        "marketer": "טוגדר",
        "manufacturer": "אוונט",
        "brand": "אוונט",
        "expiry": "12/26",
        "price": "₪135",
        "catalogPrice": "₪269",
        "parent1": "ווטרמלון ",
        "parent2": "סקיטלז",
        "originStrain": "ווטרמלון סקיטלז",
        "countryOfOrigin": "קנדה",
        "terpenes": "יומולן, קריופילן, מירצן, פיינן, לימונן",
        "packageType": "שקית"
    },
    {
        "name": "אור ג'י.בי",
        "enName": "Or G.B",
        "isNew": false,
        "rating": "(2) 1.5",
        "deal": "",
        "marketer": "טוגדר",
        "manufacturer": "",
        "brand": "טוגדר",
        "expiry": "01/27",
        "price": "₪149",
        "catalogPrice": "₪329",
        "parent1": "גלוברי",
        "parent2": "אוג'י קוש  ",
        "originStrain": "גלוברי או ג'י",
        "countryOfOrigin": "ישראל",
        "terpenes": "",
        "packageType": "שקית"
    },
    {
        "name": "איי.וי.ג'י-אס",
        "enName": "A.V.G-S",
        "isNew": false,
        "rating": "(2) 2.5",
        "deal": "",
        "marketer": "טוגדר",
        "manufacturer": "אוונט",
        "brand": "אוונט",
        "expiry": "11/26",
        "price": "₪149",
        "catalogPrice": "₪349",
        "parent1": "סקיטלז",
        "parent2": "אפלז אנד בננז",
        "originStrain": "אייוי גז",
        "countryOfOrigin": "קנדה",
        "terpenes": "",
        "packageType": "שקית"
    },
    {
        "name": "סלאק",
        "enName": "Slac",
        "isNew": false,
        "rating": "(3) 2.7",
        "deal": "",
        "marketer": "טוגדר",
        "manufacturer": "",
        "brand": "טוגדר",
        "expiry": "02/27",
        "price": "₪149",
        "catalogPrice": "₪399",
        "parent1": "אוג'י קוש ברת'",
        "parent2": "גויאבה ג'לאטו",
        "originStrain": "קריביאן קוקיז",
        "countryOfOrigin": "ישראל",
        "terpenes": "לינאלול, קריופילן, מירצן, לימונן, פיינן",
        "packageType": "שקית"
    },
    {
        "name": "פלורו",
        "enName": "Floro",
        "isNew": true,
        "rating": "(1) 2",
        "deal": "",
        "marketer": "טוגדר",
        "manufacturer": "",
        "brand": "טוגדר",
        "expiry": "04/27",
        "price": "₪149",
        "catalogPrice": "₪219",
        "parent1": "בננה אוג'י קוש",
        "parent2": "סורבה",
        "originStrain": "בננה סורבה",
        "countryOfOrigin": "קנדה",
        "terpenes": "מירצן, לימונן, קריופילן",
        "packageType": "שקית"
    },
    {
        "name": "דון-בי",
        "enName": "Don-B",
        "isNew": false,
        "rating": "(2) 5",
        "deal": "3 ב-₪449",
        "marketer": "שיח",
        "manufacturer": "",
        "brand": "שיח",
        "expiry": "02/27",
        "price": "₪159",
        "catalogPrice": "₪229",
        "parent1": "גריז מאנקי",
        "parent2": "טריפל אוג'י",
        "originStrain": "דונקי באטר",
        "countryOfOrigin": "קנדה",
        "terpenes": "לינאלול 11%, יומולן 8%, קריופילן 24%, לימונן 26%, פיינן 15%",
        "packageType": "שקית"
    },
    {
        "name": "לאסק",
        "enName": "Lask",
        "isNew": false,
        "rating": "(2) 5",
        "deal": "3 ב-₪449",
        "marketer": "שיח",
        "manufacturer": "",
        "brand": "שיח",
        "expiry": "11/26",
        "price": "₪159",
        "catalogPrice": "₪229",
        "parent1": "קרים",
        "parent2": "אל.איי קוש קייק",
        "originStrain": "קרים קייק",
        "countryOfOrigin": "קנדה",
        "terpenes": "פרנסן 18%, לינאלול 7%, יומולן 8%, קריופילן 35%, מירצן 13%, לימונן 9%, ביסבולול 4%",
        "packageType": "שקית"
    },
    {
        "name": "אסטרו אף.סי.די",
        "enName": "Astro F.C.D",
        "isNew": true,
        "rating": "(4) 3",
        "deal": "",
        "marketer": "טוגדר",
        "manufacturer": "סיקסטי סבן סינס",
        "brand": "אסטרו",
        "expiry": "03/27",
        "price": "₪169",
        "catalogPrice": "₪199",
        "parent1": "איי קנדי",
        "parent2": "אפלז אנד בננז",
        "originStrain": "פאסאד",
        "countryOfOrigin": "קנדה",
        "terpenes": "",
        "packageType": "שקית"
    },
    {
        "name": "ג'י.אר.אל.זי",
        "enName": "G.R.L.Z",
        "isNew": false,
        "rating": "(4) 4.2",
        "deal": "",
        "marketer": "טוגדר",
        "manufacturer": "סי3",
        "brand": "טוגדר",
        "expiry": "02/27",
        "price": "₪169",
        "catalogPrice": "₪209",
        "parent1": "ג'י אם או ",
        "parent2": "סקיטלז",
        "originStrain": "גרליק סקיטלז",
        "countryOfOrigin": "קנדה",
        "terpenes": "",
        "packageType": "שקית"
    },
    {
        "name": "ג'י.פי.טי סמול",
        "enName": "G.P.T Small",
        "isNew": false,
        "rating": "(5) 3",
        "deal": "",
        "marketer": "טוגדר",
        "manufacturer": "סי3",
        "brand": "טוגדר",
        "expiry": "02/27",
        "price": "₪169",
        "catalogPrice": "₪269",
        "parent1": "סטרוברי בננה  ",
        "parent2": "פרויו",
        "originStrain": "סטרוברי פרויו",
        "countryOfOrigin": "קנדה",
        "terpenes": "מירצן 33%, פיינן 28%, אוסימן 16%",
        "packageType": "שקית"
    },
    {
        "name": "קאטה",
        "enName": "Kata",
        "isNew": true,
        "rating": "(1) 5",
        "deal": "",
        "marketer": "טוגדר",
        "manufacturer": "",
        "brand": "טוגדר",
        "expiry": "01/27",
        "price": "₪169",
        "catalogPrice": "₪199",
        "parent1": "פיור מישיגן",
        "parent2": "ראנטז",
        "originStrain": "קאדילק ריינבו",
        "countryOfOrigin": "ישראל",
        "terpenes": "מירצן, קריופילן",
        "packageType": "שקית"
    },
    {
        "name": "בי.סי.אר",
        "enName": "B.C.R",
        "isNew": false,
        "rating": "(3) 2.7",
        "deal": "",
        "marketer": "טוגדר",
        "manufacturer": "דיקאר",
        "brand": "ג'יי אר סטריין",
        "expiry": "11/26",
        "price": "₪175",
        "catalogPrice": "₪349",
        "parent1": "בננה אוג'י קוש",
        "parent2": "קוקיז אנד קרים   ",
        "originStrain": "בננה קרים",
        "countryOfOrigin": "קנדה",
        "terpenes": "לינאלול, מירצן, פיינן",
        "packageType": ""
    },
    {
        "name": "רוקס אם פי מיני",
        "enName": "Rox MP Mini",
        "isNew": true,
        "rating": "(0)",
        "deal": "",
        "marketer": "טוגדר",
        "manufacturer": "רוקסטון",
        "brand": "רוקסטון",
        "expiry": "04/27",
        "price": "₪175",
        "catalogPrice": "₪349",
        "parent1": "פנקייקס",
        "parent2": "מקפלרי",
        "originStrain": "פלאפ ג'קס",
        "countryOfOrigin": "קנדה",
        "terpenes": "פרנסן, לינאלול, קריופילן, לימונן, מירצן",
        "packageType": "שקית"
    },
    {
        "name": "אורזקי מיני",
        "enName": "Orzki Mini",
        "isNew": false,
        "rating": "(1) 2",
        "deal": "3 ב-₪525",
        "marketer": "שיח",
        "manufacturer": "",
        "brand": "שיח",
        "expiry": "10/26",
        "price": "₪179",
        "catalogPrice": "₪269",
        "parent1": "אנימל מינטס",
        "parent2": "אורנג' סקיטלז",
        "originStrain": "מנגו מינט",
        "countryOfOrigin": "קנדה",
        "terpenes": "טרפינאול 5.5%, פנצ'ול 7%, פרנסן 6%, לינאלול 11%, יומולן 5.5%, קריופילן 17%, לימונן 24%, מירצן 5%",
        "packageType": "שקית"
    },
    {
        "name": "ג'י.פי.איי.אי מיני",
        "enName": "G.P.I.E Mini",
        "isNew": true,
        "rating": "(2) 3.5",
        "deal": "",
        "marketer": "טוגדר",
        "manufacturer": "",
        "brand": "טוגדר",
        "expiry": "02/27",
        "price": "₪179",
        "catalogPrice": "₪329",
        "parent1": "ג'לאטי",
        "parent2": "קוש מינטס  ",
        "originStrain": "ג'ורג'יה פאי",
        "countryOfOrigin": "קנדה",
        "terpenes": "לינאלול, קריופילן, מירצן, לימונן, פיינן",
        "packageType": "שקית"
    },
    {
        "name": "פרפל דידי מיני",
        "enName": "Purple DD Mini",
        "isNew": false,
        "rating": "(1) 4",
        "deal": "3 ב-₪525",
        "marketer": "שיח",
        "manufacturer": "",
        "brand": "שיח",
        "expiry": "11/26",
        "price": "₪179",
        "catalogPrice": "₪279",
        "parent1": "גרנדדי פרפל  ",
        "parent2": "בננה דדי",
        "originStrain": "",
        "countryOfOrigin": "קנדה",
        "terpenes": "אוסימן 13.5%, יומולן 5%, קריופילן 17%, מירצן 40%, פיינן 12%, ביסבולול 2%",
        "packageType": "שקית"
    },
    {
        "name": "טיימס",
        "enName": "Thames",
        "isNew": true,
        "rating": "(0)",
        "deal": "3 ב-₪525",
        "marketer": "קנטק",
        "manufacturer": "",
        "brand": "קנאוורו",
        "expiry": "12/26",
        "price": "₪189",
        "catalogPrice": "₪249",
        "parent1": "אוראוז",
        "parent2": "סופר בוף",
        "originStrain": "סאב זירו",
        "countryOfOrigin": "ישראל",
        "terpenes": "",
        "packageType": "שקית"
    },
    {
        "name": "אסטרו קאפ",
        "enName": "Astro Cap",
        "isNew": false,
        "rating": "(22) 4",
        "deal": "",
        "marketer": "טוגדר",
        "manufacturer": "סיקסטי סבן סינס",
        "brand": "אסטרו",
        "expiry": "11/26",
        "price": "₪199",
        "catalogPrice": "₪299",
        "parent1": "קוש מינטס  ",
        "parent2": "אליאן קוקיז  ",
        "originStrain": "קאפ ג'אנקי",
        "countryOfOrigin": "קנדה",
        "terpenes": "לינאלול 9%, קריופילן 31%, לימונן 43%",
        "packageType": "שקית"
    },
    {
        "name": "בי.יו.סי אס 1 מיני",
        "enName": "B.U.C S1 Mini",
        "isNew": true,
        "rating": "(0)",
        "deal": "3 ב-₪579",
        "marketer": "טריכום",
        "manufacturer": "טריכום",
        "brand": "טריכום",
        "expiry": "02/27",
        "price": "₪199",
        "catalogPrice": "₪289",
        "parent1": "ליט אוג'י",
        "parent2": "סטרוברי בננה  ",
        "originStrain": "גז פרוט",
        "countryOfOrigin": "ישראל",
        "terpenes": "",
        "packageType": "שקית"
    },
    {
        "name": "בלאק קלובר מיני",
        "enName": "Black Clover Mini",
        "isNew": false,
        "rating": "(2) 4",
        "deal": "",
        "marketer": "טוגדר",
        "manufacturer": "טריכום",
        "brand": "טוגדר",
        "expiry": "01/27",
        "price": "₪199",
        "catalogPrice": "₪279",
        "parent1": "שוקולד מינט אוג'י",
        "parent2": "אמנזיה באבל",
        "originStrain": "בלאק מינט",
        "countryOfOrigin": "ישראל",
        "terpenes": "",
        "packageType": "שקית"
    },
    {
        "name": "ג'.ו.נ.י כ-תום",
        "enName": "J.O.N.Y Ka-tom",
        "isNew": true,
        "rating": "(0)",
        "deal": "3 ב-₪579",
        "marketer": "עו\"ד תום דקל-שמחי",
        "manufacturer": "",
        "brand": "באבל",
        "expiry": "04/27",
        "price": "₪199",
        "catalogPrice": "₪229",
        "parent1": "אוראוז",
        "parent2": "מנדו ברת'",
        "originStrain": "פיור מישיגן",
        "countryOfOrigin": "ישראל",
        "terpenes": "",
        "packageType": "שקית"
    },
    {
        "name": "ג'י אם או.טי",
        "enName": "GMO.T",
        "isNew": false,
        "rating": "(4) 2",
        "deal": "3 ב-₪579",
        "marketer": "קנאבר",
        "manufacturer": "קנאבר",
        "brand": "קנאבר",
        "expiry": "11/26",
        "price": "₪199",
        "catalogPrice": "₪399",
        "parent1": "גריז מאנקי",
        "parent2": "טינה",
        "originStrain": "סליפרי סוזן",
        "countryOfOrigin": "ישראל",
        "terpenes": "נרולידול, מירצן, לימונן, קריופילן",
        "packageType": "שקית"
    },
    {
        "name": "דאבליו.אם.זד",
        "enName": "W.M.Z",
        "isNew": false,
        "rating": "(2) 3.5",
        "deal": "",
        "marketer": "טוגדר",
        "manufacturer": "אוונט",
        "brand": "אוונט",
        "expiry": "09/26",
        "price": "₪199",
        "catalogPrice": "₪399",
        "parent1": "ווטרמלון ",
        "parent2": "סקיטלז",
        "originStrain": "ווטרמלון סקיטלז",
        "countryOfOrigin": "קנדה",
        "terpenes": "יומולן, קריופילן, מירצן, פיינן, לימונן",
        "packageType": "שקית"
    },
    {
        "name": "ויולקס",
        "enName": "Violex",
        "isNew": false,
        "rating": "(9) 3.8",
        "deal": "3 ב-₪579",
        "marketer": "טריכום",
        "manufacturer": "טריכום",
        "brand": "טריכום",
        "expiry": "10/26",
        "price": "₪199",
        "catalogPrice": "₪389",
        "parent1": "אסאי שרבט",
        "parent2": "ג'לי ראנצ'ר",
        "originStrain": "",
        "countryOfOrigin": "ישראל",
        "terpenes": "",
        "packageType": "שקית"
    },
    {
        "name": "זוריקאן",
        "enName": "Zurican",
        "isNew": false,
        "rating": "(1) 2",
        "deal": "",
        "marketer": "טוגדר",
        "manufacturer": "דיקאר",
        "brand": "ג'יי אר סטריין",
        "expiry": "11/26",
        "price": "₪199",
        "catalogPrice": "₪399",
        "parent1": "קוקיז אנד קרים   ",
        "parent2": "סאנדיי דרייבר",
        "originStrain": "זין הוריקן",
        "countryOfOrigin": "קנדה",
        "terpenes": "קריופילן, מירצן, לימונן",
        "packageType": "שקית"
    },
    {
        "name": "מיזו",
        "enName": "Mizo",
        "isNew": false,
        "rating": "(3) 5",
        "deal": "3 ב-₪579",
        "marketer": "קול",
        "manufacturer": "קול",
        "brand": "קול",
        "expiry": "06/26",
        "price": "₪199",
        "catalogPrice": "₪369",
        "parent1": "גירל סקאוט קוקיז",
        "parent2": "כמדוג",
        "originStrain": "כם קוקיז",
        "countryOfOrigin": "ישראל",
        "terpenes": "קריופילן, לימונן, מירצן",
        "packageType": "שקית"
    },
    {
        "name": "פזו",
        "enName": "Pezzo",
        "isNew": false,
        "rating": "(9) 3.3",
        "deal": "3 ב-₪579",
        "marketer": "טריכום",
        "manufacturer": "טריכום",
        "brand": "טריכום",
        "expiry": "10/26",
        "price": "₪199",
        "catalogPrice": "₪389",
        "parent1": "פיץ' קרשנדו",
        "parent2": "פיץ' אוז",
        "originStrain": "",
        "countryOfOrigin": "ישראל",
        "terpenes": "לינאלול 10%, קריופילן 9%, פיינן 4%, לימונן 55%, מירצן 5%",
        "packageType": "שקית"
    },
    {
        "name": "ריקוטי",
        "enName": "Ricotti",
        "isNew": false,
        "rating": "(8) 4.5",
        "deal": "3 ב-₪579",
        "marketer": "טריכום",
        "manufacturer": "טריכום",
        "brand": "טריכום",
        "expiry": "11/26",
        "price": "₪199",
        "catalogPrice": "₪369",
        "parent1": "קוש מינטס  ",
        "parent2": "ג'לאטי",
        "originStrain": "סטיקי באנז",
        "countryOfOrigin": "ישראל",
        "terpenes": "לינאלול 16%, לימונן 29%, קריופילן 25%",
        "packageType": "שקית"
    },
    {
        "name": "אסטרו 33 מיני",
        "enName": "Astro 33 Mini",
        "isNew": false,
        "rating": "(0)",
        "deal": "",
        "marketer": "טוגדר",
        "manufacturer": "סיקסטי סבן סינס",
        "brand": "אסטרו",
        "expiry": "02/27",
        "price": "₪209",
        "catalogPrice": "₪299",
        "parent1": "ת'ין מינט קוקיז",
        "parent2": "סאנסט שרבט  ",
        "originStrain": "ג'לאטו #33",
        "countryOfOrigin": "קנדה",
        "terpenes": "קריופילן, לימונן, מירצן",
        "packageType": "שקית"
    },
    {
        "name": "אייץ' ריין מיני",
        "enName": "HRain Mini",
        "isNew": false,
        "rating": "(1) 4",
        "deal": "2 ב-₪420",
        "marketer": "שיח",
        "manufacturer": "מיל קריק גרוות'",
        "brand": "שיח",
        "expiry": "08/26",
        "price": "₪219",
        "catalogPrice": "₪269",
        "parent1": "הוואיין ריין",
        "parent2": "פרמננט מרקר",
        "originStrain": "הוואיין מרקר",
        "countryOfOrigin": "קנדה",
        "terpenes": "סלינה 11%, לינאלול 8%, קריופילן 9.5%, מירצן 6.5%, פיינן 7.5%, לימונן 12.5%, גרמצרן 9.5%",
        "packageType": "שקית"
    },
    {
        "name": "דאבליו.אר",
        "enName": "W.R",
        "isNew": false,
        "rating": "(7) 4.9",
        "deal": "2 ב-₪420",
        "marketer": "קנאבר",
        "manufacturer": "קנאבר",
        "brand": "קנאבר",
        "expiry": "11/26",
        "price": "₪219",
        "catalogPrice": "₪450",
        "parent1": "ראנטז",
        "parent2": "דה ווייט",
        "originStrain": "ווייט ראנטז",
        "countryOfOrigin": "ישראל",
        "terpenes": "קריופילן, לימונן, לינאלול",
        "packageType": "שקית"
    },
    {
        "name": "דבליו 56",
        "enName": "W56",
        "isNew": true,
        "rating": "(0)",
        "deal": "2 ב-₪420",
        "marketer": "קרונוס",
        "manufacturer": "קרונוס",
        "brand": "פיס נטורלס",
        "expiry": "11/27",
        "price": "₪219",
        "catalogPrice": "₪309",
        "parent1": "אנימל מינטס",
        "parent2": "פייס אוף אוג'י",
        "originStrain": "אנימל פייס",
        "countryOfOrigin": "ישראל",
        "terpenes": "יומולן, קריופילן, מירצן, לימונן, לינאלול",
        "packageType": "צנצנת"
    },
    {
        "name": "טיקי זואפי",
        "enName": "Tiki Zoapi",
        "isNew": true,
        "rating": "(2) 3",
        "deal": "2 ב-₪420",
        "marketer": "טוגדר",
        "manufacturer": "סיקסטי סבן סינס",
        "brand": "טים טיקי",
        "expiry": "04/27",
        "price": "₪219",
        "catalogPrice": "₪249",
        "parent1": "זואפ",
        "parent2": "גושרס",
        "originStrain": "זואפינייטור",
        "countryOfOrigin": "קנדה",
        "terpenes": "קריופילן, לימונן, יומולן",
        "packageType": "שקית"
    },
    {
        "name": "קונגו",
        "enName": "Congo",
        "isNew": true,
        "rating": "(0)",
        "deal": "2 ב-₪420",
        "marketer": "קנטק",
        "manufacturer": "",
        "brand": "קנאוורו",
        "expiry": "12/26",
        "price": "₪219",
        "catalogPrice": "₪249",
        "parent1": "דולצ'ה דה אווה",
        "parent2": "שרבאנגר",
        "originStrain": "בלאק מייפל",
        "countryOfOrigin": "ישראל",
        "terpenes": "",
        "packageType": "שקית"
    },
    {
        "name": "אף ג'י מיני",
        "enName": "FG Mini",
        "isNew": true,
        "rating": "(1) 3",
        "deal": "2 ב-₪420",
        "marketer": "פלאנטק",
        "manufacturer": "פלאנטק",
        "brand": "פלאנטק",
        "expiry": "12/26",
        "price": "₪229",
        "catalogPrice": "₪299",
        "parent1": "גירל סקאוט קוקיז",
        "parent2": "פייר אוג'י ",
        "originStrain": "פייר קוקיז",
        "countryOfOrigin": "ישראל",
        "terpenes": "",
        "packageType": "שקית"
    },
    {
        "name": "אריאה",
        "enName": "Aria",
        "isNew": false,
        "rating": "(6) 3",
        "deal": "2 ב-₪420",
        "marketer": "מדוקאן",
        "manufacturer": "מדוקאן",
        "brand": "סבן",
        "expiry": "09/26",
        "price": "₪239",
        "catalogPrice": "₪337",
        "parent1": "פרפל תאי",
        "parent2": "אפגני ",
        "originStrain": "בלוברי",
        "countryOfOrigin": "ישראל",
        "terpenes": "",
        "packageType": "שקית"
    },
    {
        "name": "טי.קיו.אם מיני",
        "enName": "T.Q.M Mini",
        "isNew": true,
        "rating": "(1) 4",
        "deal": "2 ב-₪420",
        "marketer": "נובה קנאביס",
        "manufacturer": "",
        "brand": "נובה קנאביס",
        "expiry": "12/26",
        "price": "₪239",
        "catalogPrice": "₪270",
        "parent1": "טריאנגל קוש",
        "parent2": "קווין אוף דה סאות'",
        "originStrain": "טריאנגל קווין",
        "countryOfOrigin": "ישראל",
        "terpenes": "לינאלול, קריופילן, מירצן, לימונן",
        "packageType": "שקית"
    },
    {
        "name": "קיו מיני",
        "enName": "Q Mini",
        "isNew": false,
        "rating": "(13) 3.8",
        "deal": "2 ב-₪420",
        "marketer": "פלאנטק",
        "manufacturer": "פלאנטק",
        "brand": "פלאנטק",
        "expiry": "02/27",
        "price": "₪239",
        "catalogPrice": "₪299",
        "parent1": "סן פרננדו ואלי אוג'י",
        "parent2": "צ'רי קוקיז",
        "originStrain": "אטומיק צ'רי",
        "countryOfOrigin": "ישראל",
        "terpenes": "לימונן, יומולן, קריופילן, פיינן",
        "packageType": "שקית"
    },
    {
        "name": "טי איי מיני",
        "enName": "TA Mini",
        "isNew": false,
        "rating": "(7) 3.7",
        "deal": "2 ב-₪420",
        "marketer": "פלאנטק",
        "manufacturer": "פלאנטק",
        "brand": "פלאנטק",
        "expiry": "01/27",
        "price": "₪245",
        "catalogPrice": "₪299",
        "parent1": "אנימל קוקיז  ",
        "parent2": "קרמל צונאמי",
        "originStrain": "אנימל צונאמי",
        "countryOfOrigin": "ישראל",
        "terpenes": "קריופילן, לימונן, מירצן",
        "packageType": "שקית"
    },
    {
        "name": "דאנטה מיני",
        "enName": "Dante Mini",
        "isNew": true,
        "rating": "(0)",
        "deal": "",
        "marketer": "שיח",
        "manufacturer": "",
        "brand": "שיח",
        "expiry": "08/27",
        "price": "₪249",
        "catalogPrice": "₪269",
        "parent1": "אוראוז",
        "parent2": "דוויל דרייבר",
        "originStrain": "דאנט'ז אינפרנו",
        "countryOfOrigin": "קנדה",
        "terpenes": "פנצ'ול 6%, יומולן 8%, קריופילן 22%, מירצן 18%, פיינן 5%, לימונן 25%, ביסבולול 4%",
        "packageType": "שקית"
    },
    {
        "name": "די בי מיני",
        "enName": "DB Mini",
        "isNew": true,
        "rating": "(0)",
        "deal": "2 ב-₪420",
        "marketer": "פלאנטק",
        "manufacturer": "פלאנטק",
        "brand": "פלאנטק",
        "expiry": "02/27",
        "price": "₪249",
        "catalogPrice": "₪299",
        "parent1": "דוג רולר",
        "parent2": "בלו גרייפ פיול",
        "originStrain": "",
        "countryOfOrigin": "ישראל",
        "terpenes": "לינאלול, קריופילן, מירצן, לימונן, יומולן",
        "packageType": "שקית"
    },
    {
        "name": "קאפ ג'אן מיניז",
        "enName": "Cap Jun Miniz",
        "isNew": false,
        "rating": "(6) 4.5",
        "deal": "",
        "marketer": "קנדוק",
        "manufacturer": "פרפלפארם",
        "brand": "פרפלפארם",
        "expiry": "02/27",
        "price": "₪249",
        "catalogPrice": "₪319",
        "parent1": "קוש מינטס  ",
        "parent2": "אליאן קוקיז  ",
        "originStrain": "קאפ ג'אנקי",
        "countryOfOrigin": "קנדה",
        "terpenes": "קריופילן, לימונן, מירצן",
        "packageType": "שקית"
    },
    {
        "name": "אורזקי",
        "enName": "Orzki",
        "isNew": false,
        "rating": "(4) 3",
        "deal": "2 ב-₪499",
        "marketer": "שיח",
        "manufacturer": "",
        "brand": "שיח",
        "expiry": "12/26",
        "price": "₪259",
        "catalogPrice": "₪369",
        "parent1": "אנימל מינטס",
        "parent2": "אורנג' סקיטלז",
        "originStrain": "מנגו מינט",
        "countryOfOrigin": "קנדה",
        "terpenes": "טרפינאול 5.5%, פנצ'ול 7%, פרנסן 6%, לינאלול 11%, יומולן 5.5%, קריופילן 17%, לימונן 24%, מירצן 5%",
        "packageType": "שקית"
    },
    {
        "name": "איי פי מיני",
        "enName": "AP Mini",
        "isNew": false,
        "rating": "(4) 3.5",
        "deal": "2 ב-₪499",
        "marketer": "פלאנטק",
        "manufacturer": "פלאנטק",
        "brand": "פלאנטק",
        "expiry": "04/27",
        "price": "₪259",
        "catalogPrice": "₪299",
        "parent1": "אפלז אנד בננז",
        "parent2": "פנקייקס",
        "originStrain": "בננה פנקייקס",
        "countryOfOrigin": "ישראל",
        "terpenes": "מירצן 22%, קריופילן 24%, לימונן 12%, לינאלול 11%, פיינן 6%, יומולן 16%",
        "packageType": "שקית"
    },
    {
        "name": "אייץ'.ריין",
        "enName": "H.Rain",
        "isNew": false,
        "rating": "(22) 4.2",
        "deal": "2 ב-₪499",
        "marketer": "שיח",
        "manufacturer": "מיל קריק גרוות'",
        "brand": "שיח",
        "expiry": "10/26",
        "price": "₪259",
        "catalogPrice": "₪369",
        "parent1": "הוואיין ריין",
        "parent2": "פרמננט מרקר",
        "originStrain": "הוואיין מרקר",
        "countryOfOrigin": "קנדה",
        "terpenes": "גרמצרן 10%, סלינה 11%, קריופילן 10%, לימונן 13%, לינאלול 8%",
        "packageType": "שקית"
    },
    {
        "name": "אסטרו בראון",
        "enName": "Astro Brown",
        "isNew": true,
        "rating": "(3) 3.7",
        "deal": "2 ב-₪499",
        "marketer": "טוגדר",
        "manufacturer": "סיקסטי סבן סינס",
        "brand": "אסטרו",
        "expiry": "04/27",
        "price": "₪259",
        "catalogPrice": "₪329",
        "parent1": "אוז קוש  ",
        "parent2": "ג'י אם או ",
        "originStrain": "קוש קוקיז",
        "countryOfOrigin": "קנדה",
        "terpenes": "קריופילן, מירצן, לימונן",
        "packageType": "שקית"
    },
    {
        "name": "אף.אף",
        "enName": "F.F",
        "isNew": false,
        "rating": "(31) 2.9",
        "deal": "2 ב-₪499",
        "marketer": "קנאבר",
        "manufacturer": "קנאבר",
        "brand": "קנאבר",
        "expiry": "11/26",
        "price": "₪259",
        "catalogPrice": "₪370",
        "parent1": "צ'רי פאי",
        "parent2": "טנג'י ",
        "originStrain": "פורבידן פרוט",
        "countryOfOrigin": "ישראל",
        "terpenes": "לינאלול, לימונן, יומולן, פיינן, מירצן, קריופילן",
        "packageType": "שקית"
    },
    {
        "name": "ג'ופ",
        "enName": "Jop",
        "isNew": false,
        "rating": "(1) 3",
        "deal": "2 ב-₪499",
        "marketer": "שיח",
        "manufacturer": "",
        "brand": "שיח",
        "expiry": "01/27",
        "price": "₪259",
        "catalogPrice": "₪349",
        "parent1": "בננה קרים פופ",
        "parent2": "ג'וקרז",
        "originStrain": "אינסייד ג'וק",
        "countryOfOrigin": "קנדה",
        "terpenes": "לינאלול 18%, יומולן 11.5%, קריופילן 34%, מירצן 8.5%, לימונן 19%, פיינן 5%",
        "packageType": "שקית"
    },
    {
        "name": "ג'י איי מיני",
        "enName": "GI Mini",
        "isNew": true,
        "rating": "(6) 4",
        "deal": "2 ב-₪499",
        "marketer": "פלאנטק",
        "manufacturer": "פלאנטק",
        "brand": "פלאנטק",
        "expiry": "01/27",
        "price": "₪259",
        "catalogPrice": "₪299",
        "parent1": "אייסי שרבט",
        "parent2": "גויאבה",
        "originStrain": "",
        "countryOfOrigin": "ישראל",
        "terpenes": "לינאלול, מירצן, פיינן, לימונן, קריופילן",
        "packageType": "שקית"
    },
    {
        "name": "זנגריה מיני",
        "enName": "Zengeria Mini",
        "isNew": true,
        "rating": "(0)",
        "deal": "",
        "marketer": "איי.אמ.סי",
        "manufacturer": "אוונט",
        "brand": "בלק מרקט",
        "expiry": "01/27",
        "price": "₪259",
        "catalogPrice": "₪289",
        "parent1": "סקיטלז",
        "parent2": "ת'ין מינט קוקיז",
        "originStrain": "זנגריה",
        "countryOfOrigin": "קנדה",
        "terpenes": "מירצן, לימונן, קריופילן",
        "packageType": "שקית"
    },
    {
        "name": "בי.יו.סי אס 1",
        "enName": "B.U.C S1",
        "isNew": false,
        "rating": "(18) 2.7",
        "deal": "",
        "marketer": "טריכום",
        "manufacturer": "טריכום",
        "brand": "טריכום",
        "expiry": "09/26",
        "price": "₪266",
        "catalogPrice": "₪400",
        "parent1": "ליט אוג'י",
        "parent2": "סטרוברי בננה  ",
        "originStrain": "גז פרוט",
        "countryOfOrigin": "ישראל",
        "terpenes": "",
        "packageType": "שקית"
    },
    {
        "name": "אר.אס.סי מיני",
        "enName": "R.S.C Mini",
        "isNew": false,
        "rating": "(1) 3",
        "deal": "",
        "marketer": "טוגדר",
        "manufacturer": "קנאדו",
        "brand": "קנאדו",
        "expiry": "02/27",
        "price": "₪269",
        "catalogPrice": "₪299",
        "parent1": "ריינבו שרבט",
        "parent2": "קאפ ג'אנקי",
        "originStrain": "",
        "countryOfOrigin": "ישראל",
        "terpenes": "",
        "packageType": "שקית"
    },
    {
        "name": "גזית",
        "enName": "Gazit",
        "isNew": true,
        "rating": "(1) 4",
        "deal": "",
        "marketer": "שוגר ליף קאן",
        "manufacturer": "קנאדו",
        "brand": "שוגר ליף קאן",
        "expiry": "02/27",
        "price": "₪269",
        "catalogPrice": "₪299",
        "parent1": "פייס מינטס",
        "parent2": "ג'לי קייק",
        "originStrain": "גז פייס",
        "countryOfOrigin": "ישראל",
        "terpenes": "מירצן, לימונן, פיינן",
        "packageType": "שקית"
    },
    {
        "name": "ג'י.אל.טי",
        "enName": "G.L.T",
        "isNew": false,
        "rating": "(9) 3",
        "deal": "2 ב-₪499",
        "marketer": "טוגדר",
        "manufacturer": "סי3",
        "brand": "טוגדר",
        "expiry": "02/27",
        "price": "₪269",
        "catalogPrice": "₪329",
        "parent1": "ווטרמלון ג'לאטו",
        "parent2": "פרוסטד צ'רי קוקיז",
        "originStrain": "פרוסטד מלון ג'לאטו",
        "countryOfOrigin": "קנדה",
        "terpenes": "קריופילן 17%, מירצן 23%, לימונן 31%, אוסימן 15%",
        "packageType": "שקית"
    },
    {
        "name": "טיקי סי.סי.אקס",
        "enName": "Tiki C.C.X",
        "isNew": false,
        "rating": "(2) 1.5",
        "deal": "",
        "marketer": "טוגדר",
        "manufacturer": "סיקסטי סבן סינס",
        "brand": "טים טיקי",
        "expiry": "10/26",
        "price": "₪269",
        "catalogPrice": "₪399",
        "parent1": "ווייט ראנטז",
        "parent2": "ראנטז",
        "originStrain": "קפטן קולד",
        "countryOfOrigin": "קנדה",
        "terpenes": "קריופילן, לימונן, פיינן",
        "packageType": "שקית"
    },
    {
        "name": "פי.אן.קיי.טי",
        "enName": "P.N.K.T",
        "isNew": true,
        "rating": "(0)",
        "deal": "",
        "marketer": "טוגדר",
        "manufacturer": "",
        "brand": "טוגדר",
        "expiry": "04/27",
        "price": "₪269",
        "catalogPrice": "₪299",
        "parent1": "וואפ",
        "parent2": "זואפ",
        "originStrain": "פינק קיטי",
        "countryOfOrigin": "קנדה",
        "terpenes": "גרמצרן, לינאלול, לימונן, פרנסן",
        "packageType": "שקית"
    },
    {
        "name": "בי.יו.סי מארקר מיני",
        "enName": "B.U.C Marker Mini",
        "isNew": false,
        "rating": "(8) 2.6",
        "deal": "2 ב-₪555",
        "marketer": "טריכום",
        "manufacturer": "טריכום",
        "brand": "טריכום",
        "expiry": "11/26",
        "price": "₪279",
        "catalogPrice": "₪319",
        "parent1": "פאקמן",
        "parent2": "סאנסט שרבט  ",
        "originStrain": "פרמננט מרקר",
        "countryOfOrigin": "ישראל",
        "terpenes": "",
        "packageType": "צנצנת"
    },
    {
        "name": "טיקי אס.פי",
        "enName": "Tiki S.P",
        "isNew": false,
        "rating": "(5) 2.6",
        "deal": "",
        "marketer": "טוגדר",
        "manufacturer": "סיקסטי סבן סינס",
        "brand": "טים טיקי",
        "expiry": "11/26",
        "price": "₪279",
        "catalogPrice": "₪399",
        "parent1": "סלוריקיין",
        "parent2": "פנקייקס",
        "originStrain": "סלוריקיין פנקייק",
        "countryOfOrigin": "קנדה",
        "terpenes": "מירצן, לימונן, קריופילן",
        "packageType": "שקית"
    },
    {
        "name": "סי.אל.אקס",
        "enName": "C.L.X",
        "isNew": true,
        "rating": "(0)",
        "deal": "",
        "marketer": "טוגדר",
        "manufacturer": "",
        "brand": "טוגדר",
        "expiry": "01/27",
        "price": "₪279",
        "catalogPrice": "₪399",
        "parent1": "פיור מישיגן",
        "parent2": "ראנטז",
        "originStrain": "קאדילק ריינבו",
        "countryOfOrigin": "קנדה",
        "terpenes": "לינאלול, קריופילן, מירצן, לימונן, פיינן",
        "packageType": "שקית"
    },
    {
        "name": "פינק סלוריקיין",
        "enName": "Pink Slurricane",
        "isNew": false,
        "rating": "(5) 2.6",
        "deal": "",
        "marketer": "טוגדר",
        "manufacturer": "סי3",
        "brand": "טוגדר",
        "expiry": "02/27",
        "price": "₪279",
        "catalogPrice": "₪329",
        "parent1": "פינק קוש  ",
        "parent2": "סלוריקיין",
        "originStrain": "פינק סלוריקיין",
        "countryOfOrigin": "קנדה",
        "terpenes": "קריופילן 30%, לימונן 40%, לינאלול 10%",
        "packageType": "שקית"
    },
    {
        "name": "אייץ'18",
        "enName": "H18",
        "isNew": false,
        "rating": "(54) 3.9",
        "deal": "2 ב-₪555",
        "marketer": "שיח",
        "manufacturer": "מיראקל וואלי",
        "brand": "שיח",
        "expiry": "08/27",
        "price": "₪287",
        "catalogPrice": "₪354",
        "parent1": "בלו שרבט",
        "parent2": "אוג'י קוש ברת'",
        "originStrain": "",
        "countryOfOrigin": "קנדה",
        "terpenes": "קריופילן 24%, לימונן 30%, לינאלול 10%, פיינן 9%, יומולן 10%",
        "packageType": "שקית"
    },
    {
        "name": "בי בי אס ג׳י",
        "enName": "BBSG",
        "isNew": true,
        "rating": "(1) 3",
        "deal": "2 ב-₪555",
        "marketer": "גרין בויז",
        "manufacturer": "קולטור דס סומטס",
        "brand": "גרין בויז",
        "expiry": "08/27",
        "price": "₪289",
        "catalogPrice": "₪329",
        "parent1": "גרייפ קרים 2.1",
        "parent2": "בלוברי פרוסטינג",
        "originStrain": "בלוברי שוגר",
        "countryOfOrigin": "קנדה",
        "terpenes": "",
        "packageType": "שקית"
    },
    {
        "name": "גאש",
        "enName": "Gus",
        "isNew": true,
        "rating": "(1) 5",
        "deal": "2 ב-₪555",
        "marketer": "קנאבר",
        "manufacturer": "קנאבר",
        "brand": "קנאבר",
        "expiry": "12/26",
        "price": "₪289",
        "catalogPrice": "₪370",
        "parent1": "ג'לאטו 41",
        "parent2": "טריאנגל קוש",
        "originStrain": "גושרס",
        "countryOfOrigin": "ישראל",
        "terpenes": "",
        "packageType": "שקית"
    },
    {
        "name": "פי אר",
        "enName": "PR",
        "isNew": false,
        "rating": "(13) 3.9",
        "deal": "2 ב-₪555",
        "marketer": "פלאנטק",
        "manufacturer": "פלאנטק",
        "brand": "פלאנטק",
        "expiry": "12/26",
        "price": "₪289",
        "catalogPrice": "₪379",
        "parent1": "רד ולווט",
        "parent2": "פנקייקס",
        "originStrain": "רד ולווט פנקייקס",
        "countryOfOrigin": "ישראל",
        "terpenes": "לינאלול, קריופילן, מירצן, לימונן, פיינן",
        "packageType": "שקית"
    },
    {
        "name": "פרפל דידי",
        "enName": "Purple DD",
        "isNew": false,
        "rating": "(7) 4",
        "deal": "2 ב-₪555",
        "marketer": "שיח",
        "manufacturer": "",
        "brand": "שיח",
        "expiry": "12/26",
        "price": "₪289",
        "catalogPrice": "₪369",
        "parent1": "גרנדדי פרפל  ",
        "parent2": "בננה דדי",
        "originStrain": "",
        "countryOfOrigin": "קנדה",
        "terpenes": "אוסימן 13.5%, יומולן 5%, קריופילן 17%, מירצן 40%, פיינן 12%, ביסבולול 2%",
        "packageType": "שקית"
    },
    {
        "name": "אסטרו 33",
        "enName": "Astro 33",
        "isNew": false,
        "rating": "(18) 4",
        "deal": "",
        "marketer": "טוגדר",
        "manufacturer": "סיקסטי סבן סינס",
        "brand": "אסטרו",
        "expiry": "09/26",
        "price": "₪299",
        "catalogPrice": "₪379",
        "parent1": "ת'ין מינט קוקיז",
        "parent2": "סאנסט שרבט  ",
        "originStrain": "ג'לאטו #33",
        "countryOfOrigin": "קנדה",
        "terpenes": "קריופילן, לימונן, מירצן",
        "packageType": "שקית"
    },
    {
        "name": "בלאק קלובר",
        "enName": "Black Clover",
        "isNew": false,
        "rating": "(18) 3.6",
        "deal": "",
        "marketer": "טוגדר",
        "manufacturer": "טריכום",
        "brand": "טוגדר",
        "expiry": "10/26",
        "price": "₪299",
        "catalogPrice": "₪379",
        "parent1": "שוקולד מינט אוג'י",
        "parent2": "אמנזיה באבל",
        "originStrain": "בלאק מינט",
        "countryOfOrigin": "ישראל",
        "terpenes": "",
        "packageType": "שקית"
    },
    {
        "name": "גרין קלובר",
        "enName": "Green Clover",
        "isNew": false,
        "rating": "(74) 3.5",
        "deal": "",
        "marketer": "טוגדר",
        "manufacturer": "טריכום",
        "brand": "טוגדר",
        "expiry": "10/26",
        "price": "₪299",
        "catalogPrice": "₪389",
        "parent1": "ג'לאטו ",
        "parent2": "גושרס",
        "originStrain": "ג'לאטו 41",
        "countryOfOrigin": "ישראל",
        "terpenes": "קריופילן, פיינן, מירצן, לימונן",
        "packageType": "שקית"
    },
    {
        "name": "טיקי אס.אן.דאבליו",
        "enName": "Tiki S.N.W",
        "isNew": false,
        "rating": "(14) 3.4",
        "deal": "2 ב-₪555",
        "marketer": "טוגדר",
        "manufacturer": "סיקסטי סבן סינס",
        "brand": "טים טיקי",
        "expiry": "10/26",
        "price": "₪299",
        "catalogPrice": "₪399",
        "parent1": "הוואיין סנואוקון",
        "parent2": "בלוברי סקיטלז",
        "originStrain": "בלוברי סנואוקון",
        "countryOfOrigin": "קנדה",
        "terpenes": "לימונן, מירצן",
        "packageType": "שקית"
    },
    {
        "name": "טיקי ג'י.או.סי",
        "enName": "Tiki G.O.C",
        "isNew": false,
        "rating": "(4) 4",
        "deal": "",
        "marketer": "טוגדר",
        "manufacturer": "סיקסטי סבן סינס",
        "brand": "טים טיקי",
        "expiry": "10/26",
        "price": "₪299",
        "catalogPrice": "₪399",
        "parent1": "פאפא'ס קנדי",
        "parent2": "גורילה גלו  ",
        "originStrain": "גורילה קנדי",
        "countryOfOrigin": "קנדה",
        "terpenes": "קריופילן, לימונן, לינאלול",
        "packageType": "שקית"
    },
    {
        "name": "טיקי ג'י-מנטז",
        "enName": "Tiki G-MNTZ",
        "isNew": false,
        "rating": "(5) 1.6",
        "deal": "",
        "marketer": "טוגדר",
        "manufacturer": "סיקסטי סבן סינס",
        "brand": "טים טיקי",
        "expiry": "08/26",
        "price": "₪299",
        "catalogPrice": "₪399",
        "parent1": "ג'לאטי",
        "parent2": "קוש מינטס  ",
        "originStrain": "ג'לאטי מינטז",
        "countryOfOrigin": "קנדה",
        "terpenes": "לינאלול, לימונן, קריופילן",
        "packageType": "שקית"
    },
    {
        "name": "טיקי דאנטה",
        "enName": "Tiki Dante",
        "isNew": false,
        "rating": "(11) 3.3",
        "deal": "",
        "marketer": "טוגדר",
        "manufacturer": "סיקסטי סבן סינס",
        "brand": "טים טיקי",
        "expiry": "04/27",
        "price": "₪299",
        "catalogPrice": "₪399",
        "parent1": "אוראוז",
        "parent2": "דוויל דרייבר",
        "originStrain": "דאנט'ז אינפרנו",
        "countryOfOrigin": "קנדה",
        "terpenes": "ביסבולול, לימונן, מירצן",
        "packageType": "שקית"
    },
    {
        "name": "טי.קיו",
        "enName": "T.Q",
        "isNew": false,
        "rating": "(4) 4",
        "deal": "2 ב-₪599",
        "marketer": "נובה קנאביס",
        "manufacturer": "",
        "brand": "נובה קנאביס",
        "expiry": "10/26",
        "price": "₪309",
        "catalogPrice": "₪389",
        "parent1": "טריאנגל קוש",
        "parent2": "קווין אוף דה סאות'",
        "originStrain": "טריאנגל קווין",
        "countryOfOrigin": "ישראל",
        "terpenes": "לינאלול, קריופילן, מירצן, לימונן",
        "packageType": "שקית"
    },
    {
        "name": "די-931",
        "enName": "D-931",
        "isNew": true,
        "rating": "(2) 3.5",
        "deal": "2 ב-₪599",
        "marketer": "שיח",
        "manufacturer": "",
        "brand": "שיח",
        "expiry": "12/26",
        "price": "₪319",
        "catalogPrice": "₪420",
        "parent1": "גסטרו פופ",
        "parent2": "אליאן מינטס",
        "originStrain": "",
        "countryOfOrigin": "קנדה",
        "terpenes": "",
        "packageType": "שקית"
    },
    {
        "name": "קיו",
        "enName": "Q",
        "isNew": false,
        "rating": "(42) 3.8",
        "deal": "2 ב-₪599",
        "marketer": "פלאנטק",
        "manufacturer": "פלאנטק",
        "brand": "פלאנטק",
        "expiry": "02/27",
        "price": "₪319",
        "catalogPrice": "₪399",
        "parent1": "סן פרננדו ואלי אוג'י",
        "parent2": "צ'רי קוקיז",
        "originStrain": "אטומיק צ'רי",
        "countryOfOrigin": "ישראל",
        "terpenes": "מירצן 20%, קריופילן 22%, לימונן 25%, לינאלול 6%, פיינן 6%, יומולן 11%",
        "packageType": "שקית"
    },
    {
        "name": "איי פי",
        "enName": "AP",
        "isNew": false,
        "rating": "(24) 3.8",
        "deal": "2 ב-₪599",
        "marketer": "פלאנטק",
        "manufacturer": "פלאנטק",
        "brand": "פלאנטק",
        "expiry": "04/27",
        "price": "₪329",
        "catalogPrice": "₪399",
        "parent1": "אפלז אנד בננז",
        "parent2": "פנקייקס",
        "originStrain": "בננה פנקייקס",
        "countryOfOrigin": "ישראל",
        "terpenes": "מירצן 22%, קריופילן 24%, לימונן 12%, לינאלול 11%, פיינן 6%, יומולן 16%",
        "packageType": "שקית"
    },
    {
        "name": "אף ג'י",
        "enName": "FG",
        "isNew": true,
        "rating": "(1) 4",
        "deal": "2 ב-₪599",
        "marketer": "פלאנטק",
        "manufacturer": "פלאנטק",
        "brand": "פלאנטק",
        "expiry": "12/26",
        "price": "₪329",
        "catalogPrice": "₪399",
        "parent1": "גירל סקאוט קוקיז",
        "parent2": "פייר אוג'י ",
        "originStrain": "פייר קוקיז",
        "countryOfOrigin": "ישראל",
        "terpenes": "",
        "packageType": "שקית"
    },
    {
        "name": "ג'י.אם.או.אס",
        "enName": "GMO.S",
        "isNew": false,
        "rating": "(19) 3.8",
        "deal": "",
        "marketer": "קנדוק",
        "manufacturer": "פרפלפארם",
        "brand": "פרפלפארם",
        "expiry": "02/27",
        "price": "₪329",
        "catalogPrice": "₪379",
        "parent1": "ג'י אם או ",
        "parent2": "סקיטלז",
        "originStrain": "ג'י אם או סקיטלז",
        "countryOfOrigin": "קנדה",
        "terpenes": "פיינן, לימונן, מירצן, קריופילן",
        "packageType": "שקית"
    },
    {
        "name": "טי איי",
        "enName": "TA",
        "isNew": false,
        "rating": "(6) 4.2",
        "deal": "2 ב-₪599",
        "marketer": "פלאנטק",
        "manufacturer": "פלאנטק",
        "brand": "פלאנטק",
        "expiry": "12/26",
        "price": "₪329",
        "catalogPrice": "₪399",
        "parent1": "אנימל קוקיז  ",
        "parent2": "קרמל צונאמי",
        "originStrain": "אנימל צונאמי",
        "countryOfOrigin": "ישראל",
        "terpenes": "קריופילן, לימונן, מירצן",
        "packageType": "שקית"
    },
    {
        "name": "קאפ ג'אן",
        "enName": "Cap Jun",
        "isNew": false,
        "rating": "(53) 3.8",
        "deal": "",
        "marketer": "קנדוק",
        "manufacturer": "פרפלפארם",
        "brand": "פרפלפארם",
        "expiry": "02/27",
        "price": "₪329",
        "catalogPrice": "₪379",
        "parent1": "קוש מינטס  ",
        "parent2": "אליאן קוקיז  ",
        "originStrain": "קאפ ג'אנקי",
        "countryOfOrigin": "קנדה",
        "terpenes": "קריופילן, לימונן, מירצן",
        "packageType": "שקית"
    },
    {
        "name": "אף פי או ג'י",
        "enName": "‎FP‎.‎OG‎",
        "isNew": true,
        "rating": "(0)",
        "deal": "3 ב-₪999",
        "marketer": "גרין בויז",
        "manufacturer": "קולטור דס סומטס",
        "brand": "גרין בויז",
        "expiry": "08/27",
        "price": "₪339",
        "catalogPrice": "₪399",
        "parent1": "גרין ריבון",
        "parent2": "טאהו אליאן אוג'י  ",
        "originStrain": "פרוטי פבלס",
        "countryOfOrigin": "קנדה",
        "terpenes": "",
        "packageType": "שקית"
    },
    {
        "name": "די בי",
        "enName": "DB",
        "isNew": true,
        "rating": "(0)",
        "deal": "2 ב-₪599",
        "marketer": "פלאנטק",
        "manufacturer": "פלאנטק",
        "brand": "פלאנטק",
        "expiry": "02/27",
        "price": "₪339",
        "catalogPrice": "₪399",
        "parent1": "דוג רולר",
        "parent2": "בלו גרייפ פיול",
        "originStrain": "",
        "countryOfOrigin": "ישראל",
        "terpenes": "לינאלול, קריופילן, מירצן, לימונן, יומולן",
        "packageType": "שקית"
    },
    {
        "name": "טיקי ד.ר.נ.ט.ז",
        "enName": "Tiki D.R.N.T.Z",
        "isNew": false,
        "rating": "(12) 3.5",
        "deal": "",
        "marketer": "טוגדר",
        "manufacturer": "סיקסטי סבן סינס",
        "brand": "טים טיקי",
        "expiry": "02/27",
        "price": "₪339",
        "catalogPrice": "₪399",
        "parent1": "פנקייקס",
        "parent2": "ראנטז",
        "originStrain": "דטרויט ראנטז",
        "countryOfOrigin": "קנדה",
        "terpenes": "קריופילן, לימונן, לינאלול",
        "packageType": "שקית"
    },
    {
        "name": "ס.קרלה",
        "enName": "S.Krla",
        "isNew": false,
        "rating": "(11) 4.1",
        "deal": "3 ב-₪999",
        "marketer": "גרין בויז",
        "manufacturer": "קולטור דס סומטס",
        "brand": "גרין בויז",
        "expiry": "08/27",
        "price": "₪339",
        "catalogPrice": "₪429",
        "parent1": "רד פופ",
        "parent2": "ג'וקרז",
        "originStrain": "סטרוברי סקרילה",
        "countryOfOrigin": "קנדה",
        "terpenes": "אוסימן, קריופילן, מירצן, לימונן, לינאלול",
        "packageType": "שקית"
    },
    {
        "name": "קאפ ג'יי.אן.קיי",
        "enName": "CAP J.N.K",
        "isNew": true,
        "rating": "(0)",
        "deal": "3 ב-₪999",
        "marketer": "שיח",
        "manufacturer": "",
        "brand": "שיח",
        "expiry": "03/27",
        "price": "₪339",
        "catalogPrice": "₪379",
        "parent1": "קוש מינטס  ",
        "parent2": "אליאן קוקיז  ",
        "originStrain": "קאפ ג'אנקי",
        "countryOfOrigin": "קנדה",
        "terpenes": "טרפינאול, פנצ'ול, פרנסן, לינאלול, יומולן, קריופילן, לימונן, מירצן",
        "packageType": "שקית"
    },
    {
        "name": "אס.איי.פי",
        "enName": "S.A.P",
        "isNew": false,
        "rating": "(13) 4.2",
        "deal": "",
        "marketer": "טוגדר",
        "manufacturer": "",
        "brand": "טוגדר",
        "expiry": "04/27",
        "price": "₪349",
        "catalogPrice": "₪399",
        "parent1": "גורילה פיס",
        "parent2": "פרמננט מרקר",
        "originStrain": "סאן אוף אה פיץ'",
        "countryOfOrigin": "קנדה",
        "terpenes": "",
        "packageType": "שקית"
    },
    {
        "name": "אר אס 11",
        "enName": "RS11",
        "isNew": false,
        "rating": "(35) 3.4",
        "deal": "",
        "marketer": "טריכום",
        "manufacturer": "טריכום",
        "brand": "טריכום",
        "expiry": "04/27",
        "price": "₪349",
        "catalogPrice": "₪389",
        "parent1": "אוז קוש  ",
        "parent2": "פינק גויאבה",
        "originStrain": "ריינבו שרבט",
        "countryOfOrigin": "ישראל",
        "terpenes": "קריופילן 7%, לימונן 31%, לינאלול 11%, פיינן 7%, יומולן 7%",
        "packageType": "צנצנת"
    },
    {
        "name": "בלו פאבה",
        "enName": "Blue Pave",
        "isNew": false,
        "rating": "(9) 3.8",
        "deal": "",
        "marketer": "גרין בויז",
        "manufacturer": "קולטור דס סומטס",
        "brand": "גרין בויז",
        "expiry": "08/27",
        "price": "₪349",
        "catalogPrice": "₪429",
        "parent1": "פאבה",
        "parent2": "אזול ראנטז",
        "originStrain": "בלו פאבה",
        "countryOfOrigin": "קנדה",
        "terpenes": "לינאלול, מירצן, לימונן, פיינן",
        "packageType": "שקית"
    },
    {
        "name": "ויסטה",
        "enName": "Vista",
        "isNew": false,
        "rating": "(32) 4.3",
        "deal": "",
        "marketer": "טריכום",
        "manufacturer": "טריכום",
        "brand": "טריכום",
        "expiry": "03/27",
        "price": "₪349",
        "catalogPrice": "₪389",
        "parent1": "ג'לי קייק",
        "parent2": "ג'לוסי",
        "originStrain": "פרפל אוקטן",
        "countryOfOrigin": "ישראל",
        "terpenes": "יומולן 17%, קריופילן 16%, לימונן 23%",
        "packageType": "צנצנת"
    },
    {
        "name": "טריפל סי",
        "enName": "Triple C",
        "isNew": false,
        "rating": "(11) 4.4",
        "deal": "",
        "marketer": "טריכום",
        "manufacturer": "טריכום",
        "brand": "טריכום",
        "expiry": "03/27",
        "price": "₪349",
        "catalogPrice": "₪389",
        "parent1": "קימבו קוש",
        "parent2": "צ'רי פאי",
        "originStrain": "צ'רי צ'יזקייק",
        "countryOfOrigin": "ישראל",
        "terpenes": "קריופילן 25%, לימונן 20%, לינאלול 9%",
        "packageType": "צנצנת"
    },
    {
        "name": "סוויפ",
        "enName": "Swip",
        "isNew": true,
        "rating": "(0)",
        "deal": "",
        "marketer": "טריכום",
        "manufacturer": "טריכום",
        "brand": "טריכום",
        "expiry": "05/27",
        "price": "₪349",
        "catalogPrice": "₪389",
        "parent1": "גרייפ אייפ",
        "parent2": "צ'רי פאי",
        "originStrain": "",
        "countryOfOrigin": "ישראל",
        "terpenes": "",
        "packageType": "צנצנת"
    },
    {
        "name": "סי.אייץ'.אר",
        "enName": "C.H.R",
        "isNew": false,
        "rating": "(1) 5",
        "deal": "3 ב-₪999",
        "marketer": "טוגדר",
        "manufacturer": "יור היינס",
        "brand": "יור היינס",
        "expiry": "11/26",
        "price": "₪349",
        "catalogPrice": "₪479",
        "parent1": "סקיטלז",
        "parent2": "סאנסט שרבט  ",
        "originStrain": "כרומה",
        "countryOfOrigin": "קנדה",
        "terpenes": "",
        "packageType": "שקית"
    },
    {
        "name": "פי.בי מאק",
        "enName": "P.B Mac",
        "isNew": false,
        "rating": "(1) 3",
        "deal": "3 ב-₪999",
        "marketer": "טוגדר",
        "manufacturer": "אוונט",
        "brand": "אוונט",
        "expiry": "11/26",
        "price": "₪349",
        "catalogPrice": "₪419",
        "parent1": "פינט באטר ברת'   ",
        "parent2": "מירקל אליאן קוקיז   ",
        "originStrain": "פינט באטר מאק",
        "countryOfOrigin": "קנדה",
        "terpenes": "קריופילן, לימונן, פרנסן",
        "packageType": "שקית"
    },
    {
        "name": "רוקסטון אף סי",
        "enName": "Roxton FC",
        "isNew": false,
        "rating": "(7) 1.6",
        "deal": "",
        "marketer": "טוגדר",
        "manufacturer": "רוקסטון",
        "brand": "רוקסטון",
        "expiry": "01/27",
        "price": "₪349",
        "catalogPrice": "₪499",
        "parent1": "גירל סקאוט קוקיז",
        "parent2": "דה ווייט",
        "originStrain": "פרוסטד קוקיז",
        "countryOfOrigin": "קנדה",
        "terpenes": "פרנסן, יומולן, קריופילן, מירצן, לימונן",
        "packageType": "שקית"
    },
    {
        "name": "ג'י אר.פי קווסט",
        "enName": "Qwest GR.P",
        "isNew": true,
        "rating": "(0)",
        "deal": "",
        "marketer": "קרונוס",
        "manufacturer": "דציבל",
        "brand": "לורד ג'ונס",
        "expiry": "02/27",
        "price": "₪359",
        "catalogPrice": "₪399",
        "parent1": "ג'לאטי",
        "parent2": "קוש מינטס  ",
        "originStrain": "ג'ורג'יה פאי",
        "countryOfOrigin": "קנדה",
        "terpenes": "סלינן, יומולן, קריופילן, מירצן, לימונן",
        "packageType": "צנצנת"
    },
    {
        "name": "גרייפר",
        "enName": "Gryper",
        "isNew": false,
        "rating": "(6) 3.8",
        "deal": "",
        "marketer": "קרונוס",
        "manufacturer": "קרונוס",
        "brand": "לורד ג'ונס",
        "expiry": "10/26",
        "price": "₪359",
        "catalogPrice": "₪419",
        "parent1": "בלוברי ",
        "parent2": "",
        "originStrain": "גרייפ קראש",
        "countryOfOrigin": "קנדה",
        "terpenes": "פרנסן, לינאלול, מירצן, לימונן, גוואיול",
        "packageType": "צנצנת"
    },
    {
        "name": "דבליו קווסט",
        "enName": "Qwest W",
        "isNew": true,
        "rating": "(0)",
        "deal": "",
        "marketer": "קרונוס",
        "manufacturer": "דציבל",
        "brand": "לורד ג'ונס",
        "expiry": "02/27",
        "price": "₪359",
        "catalogPrice": "₪399",
        "parent1": "ווייט ווידו  ",
        "parent2": "סקייווקר ",
        "originStrain": "ווייט ווקר",
        "countryOfOrigin": "קנדה",
        "terpenes": "קימן, קריופילן, מירצן, לימונן, פיינן",
        "packageType": "צנצנת"
    },
    {
        "name": "אס.קיי.טי",
        "enName": "S.K.T",
        "isNew": false,
        "rating": "(2) 4",
        "deal": "",
        "marketer": "טוגדר",
        "manufacturer": "יור היינס",
        "brand": "יור היינס",
        "expiry": "11/26",
        "price": "₪369",
        "catalogPrice": "₪479",
        "parent1": "ג'י אם או ",
        "parent2": "אוז קוש  ",
        "originStrain": "סקאנקסט",
        "countryOfOrigin": "קנדה",
        "terpenes": "",
        "packageType": "שקית"
    },
    {
        "name": "בלק קאבר",
        "enName": "BLK Cavar",
        "isNew": true,
        "rating": "(0)",
        "deal": "",
        "marketer": "איי.אמ.סי",
        "manufacturer": "אוונט",
        "brand": "בלק מרקט",
        "expiry": "01/27",
        "price": "₪377",
        "catalogPrice": "₪419",
        "parent1": "יא המי",
        "parent2": "סן פרננדו ואלי אוג'י",
        "originStrain": "",
        "countryOfOrigin": "קנדה",
        "terpenes": "לימונן, לינאלול",
        "packageType": "שקית"
    },
    {
        "name": "זנגריה",
        "enName": "Zengeria",
        "isNew": true,
        "rating": "(1) 3",
        "deal": "",
        "marketer": "איי.אמ.סי",
        "manufacturer": "אוונט",
        "brand": "בלק מרקט",
        "expiry": "01/27",
        "price": "₪377",
        "catalogPrice": "₪419",
        "parent1": "סקיטלז",
        "parent2": "ת'ין מינט קוקיז",
        "originStrain": "זנגריה",
        "countryOfOrigin": "קנדה",
        "terpenes": "מירצן, לימונן, קריופילן",
        "packageType": "שקית"
    },
    {
        "name": "בי.יו.סי בוקוטי",
        "enName": "B.U.C Bucotti",
        "isNew": false,
        "rating": "(18) 3.1",
        "deal": "",
        "marketer": "טריכום",
        "manufacturer": "טריכום",
        "brand": "טריכום",
        "expiry": "03/27",
        "price": "₪378",
        "catalogPrice": "₪420",
        "parent1": "ביסקוטי",
        "parent2": "רד ראנטז",
        "originStrain": "טום בריידי",
        "countryOfOrigin": "ישראל",
        "terpenes": "יומולן, קריופילן, לימונן, לינאלול",
        "packageType": "צנצנת"
    },
    {
        "name": "בי.יו.סי מארקר",
        "enName": "B.U.C Marker",
        "isNew": false,
        "rating": "(89) 2.9",
        "deal": "",
        "marketer": "טריכום",
        "manufacturer": "טריכום",
        "brand": "טריכום",
        "expiry": "04/27",
        "price": "₪378",
        "catalogPrice": "₪420",
        "parent1": "פאקמן",
        "parent2": "סאנסט שרבט  ",
        "originStrain": "פרמננט מרקר",
        "countryOfOrigin": "ישראל",
        "terpenes": "",
        "packageType": "צנצנת"
    },
    {
        "name": "זופ",
        "enName": "Zoap",
        "isNew": true,
        "rating": "(1) 4",
        "deal": "",
        "marketer": "שיח",
        "manufacturer": "בלו הרבור אורגניקס",
        "brand": "קנאביס בראדרס",
        "expiry": "04/27",
        "price": "₪378",
        "catalogPrice": "₪420",
        "parent1": "ריינבו שרבט",
        "parent2": "פינק גויאבה",
        "originStrain": "זואפ",
        "countryOfOrigin": "קנדה",
        "terpenes": "",
        "packageType": "שקית"
    },
    {
        "name": "שרבאן #22",
        "enName": "Sherban #22",
        "isNew": true,
        "rating": "(1) 1",
        "deal": "",
        "marketer": "שיח",
        "manufacturer": "בלו הרבור אורגניקס",
        "brand": "קנאביס בראדרס",
        "expiry": "07/27",
        "price": "₪378",
        "catalogPrice": "₪420",
        "parent1": "סאנסט שרבט  ",
        "parent2": "הדבאנגר",
        "originStrain": "שרבאנגר",
        "countryOfOrigin": "קנדה",
        "terpenes": "",
        "packageType": "שקית"
    },
    {
        "name": "סולו אקסיס",
        "enName": "SOLO Axis",
        "isNew": true,
        "rating": "(3) 4",
        "deal": "",
        "marketer": "מדוקאן",
        "manufacturer": "מדוקאן",
        "brand": "סולו",
        "expiry": "02/27",
        "price": "₪385",
        "catalogPrice": "₪429",
        "parent1": "גושרס",
        "parent2": "קוש מינטס  ",
        "originStrain": "גוש מינטס",
        "countryOfOrigin": "ישראל",
        "terpenes": "קריופילן, לימונן, מירצן",
        "packageType": "צנצנת"
    },
    {
        "name": "סולו טריניטי",
        "enName": "SOLO Trinity",
        "isNew": false,
        "rating": "(11) 4.6",
        "deal": "",
        "marketer": "מדוקאן",
        "manufacturer": "מדוקאן",
        "brand": "סולו",
        "expiry": "01/27",
        "price": "₪385",
        "catalogPrice": "₪429",
        "parent1": "פרוטי פבלס",
        "parent2": "וודינג קייק  ",
        "originStrain": "פרוסטד פרוט קייק",
        "countryOfOrigin": "ישראל",
        "terpenes": "לינאלול, מירצן, לימונן, קריופילן",
        "packageType": "צנצנת"
    },
    {
        "name": "סולו קומט",
        "enName": "SOLO Comet",
        "isNew": true,
        "rating": "(9) 4",
        "deal": "",
        "marketer": "מדוקאן",
        "manufacturer": "מדוקאן",
        "brand": "סולו",
        "expiry": "12/26",
        "price": "₪385",
        "catalogPrice": "₪429",
        "parent1": "ג'וקרז",
        "parent2": "גסטרו פופ",
        "originStrain": "טייגרז איי",
        "countryOfOrigin": "ישראל",
        "terpenes": "קריופילן, פיינן, לימונן, מירצן",
        "packageType": "צנצנת"
    },
    {
        "name": "איי בי אן",
        "enName": "ABN",
        "isNew": false,
        "rating": "(20) 3.2",
        "deal": "",
        "marketer": "קנדוק",
        "manufacturer": "",
        "brand": "קוקיז",
        "expiry": "02/27",
        "price": "₪399",
        "catalogPrice": "₪399",
        "parent1": "נאו אן לייטר",
        "parent2": "ג'לאטי",
        "originStrain": "אפלז אנד בננז",
        "countryOfOrigin": "קנדה",
        "terpenes": "לינאלול, לימונן, קריופילן",
        "packageType": "שקית"
    },
    {
        "name": "גארי",
        "enName": "Gary",
        "isNew": false,
        "rating": "(8) 3.2",
        "deal": "",
        "marketer": "קנדוק",
        "manufacturer": "",
        "brand": "קוקיז",
        "expiry": "11/26",
        "price": "₪399",
        "catalogPrice": "₪399",
        "parent1": "וואי לייף",
        "parent2": "סנואומן ",
        "originStrain": "גארי פייטון",
        "countryOfOrigin": "קנדה",
        "terpenes": "קריופילן, יומולן, לינאלול",
        "packageType": "שקית"
    },
    {
        "name": "ג'ורג'יה פי",
        "enName": "Georgia P",
        "isNew": false,
        "rating": "(12) 4.3",
        "deal": "",
        "marketer": "קנדוק",
        "manufacturer": "",
        "brand": "קוקיז",
        "expiry": "12/26",
        "price": "₪399",
        "catalogPrice": "₪399",
        "parent1": "ג'לאטי",
        "parent2": "קוש מינטס  ",
        "originStrain": "ג'ורג'יה פאי",
        "countryOfOrigin": "קנדה",
        "terpenes": "קריופילן, לימונן, לינאלול",
        "packageType": "שקית"
    },
    {
        "name": "וואנזה",
        "enName": "Wanza",
        "isNew": false,
        "rating": "(5) 4",
        "deal": "",
        "marketer": "קנדוק",
        "manufacturer": "",
        "brand": "בינסק",
        "expiry": "11/26",
        "price": "₪420",
        "catalogPrice": "₪449",
        "parent1": "ווטרמלון ",
        "parent2": "סקיטלז",
        "originStrain": "ווטרמלון סקיטלז",
        "countryOfOrigin": "קנדה",
        "terpenes": "",
        "packageType": "שקית"
    },
    {
        "name": "טמאלז",
        "enName": "Tamalez",
        "isNew": true,
        "rating": "(1) 4",
        "deal": "",
        "marketer": "קנדוק",
        "manufacturer": "פרדייס ואלי",
        "brand": "טוטם",
        "expiry": "02/27",
        "price": "₪420",
        "catalogPrice": "₪420",
        "parent1": "צ'ילי ורדה",
        "parent2": "אובמה ראנטז",
        "originStrain": "טמאלז",
        "countryOfOrigin": "קנדה",
        "terpenes": "",
        "packageType": "שקית"
    },
    {
        "name": "סנטו",
        "enName": "Santo",
        "isNew": false,
        "rating": "(28) 3.5",
        "deal": "",
        "marketer": "קנדוק",
        "manufacturer": "קוטס קאנה",
        "brand": "טוטם",
        "expiry": "02/27",
        "price": "₪420",
        "catalogPrice": "₪449",
        "parent1": "דה מנתול",
        "parent2": "לאבה קייק  ",
        "originStrain": "אייס ברן",
        "countryOfOrigin": "קנדה",
        "terpenes": "פרנסן, נרולידול, לימונן, גרמצרן",
        "packageType": "שקית"
    },
    {
        "name": "צ'אמפה",
        "enName": "Champe",
        "isNew": false,
        "rating": "(9) 3.7",
        "deal": "",
        "marketer": "קרונוס",
        "manufacturer": "קרונוס",
        "brand": "לורד ג'ונס",
        "expiry": "11/26",
        "price": "₪425",
        "catalogPrice": "₪479",
        "parent1": "צ'רי פאי",
        "parent2": "גרנדדי פרפל  ",
        "originStrain": "פינק שמפיין",
        "countryOfOrigin": "קנדה",
        "terpenes": "פרנסן, קריופילן, מירצן, לימונן, יומולן",
        "packageType": "צנצנת"
    },
    {
        "name": "יאמאנה",
        "enName": "Yamana",
        "isNew": true,
        "rating": "(2) 4.5",
        "deal": "",
        "marketer": "קנדוק",
        "manufacturer": "קוטניי קוואנטום",
        "brand": "טוטם",
        "expiry": "02/27",
        "price": "₪449",
        "catalogPrice": "₪449",
        "parent1": "צ'רי ת'אנדר פאק",
        "parent2": "ראסטי הייז",
        "originStrain": "דארק מאטר",
        "countryOfOrigin": "קנדה",
        "terpenes": "",
        "packageType": "שקית"
    },
    {
        "name": "פוגו",
        "enName": "Fugu",
        "isNew": true,
        "rating": "(3) 2.3",
        "deal": "",
        "marketer": "טוגדר",
        "manufacturer": "",
        "brand": "טוגדר",
        "expiry": "01/27",
        "price": "₪449",
        "catalogPrice": "₪399",
        "parent1": "פוג'יווארה",
        "parent2": "קאפ ג'אנקי",
        "originStrain": "פוגו",
        "countryOfOrigin": "קנדה",
        "terpenes": "לינאלול, קריופילן, מירצן, לימונן, פיינן",
        "packageType": "שקית"
    },
    {
        "name": "פילו",
        "enName": "Pilo",
        "isNew": true,
        "rating": "(6) 3",
        "deal": "",
        "marketer": "קנדוק",
        "manufacturer": "קוטס קאנה",
        "brand": "קוטס קאנה",
        "expiry": "12/26",
        "price": "₪489",
        "catalogPrice": "₪489",
        "parent1": "פינק ראנטז",
        "parent2": "זאיזאי",
        "originStrain": "",
        "countryOfOrigin": "קנדה",
        "terpenes": "",
        "packageType": "שקית"
    },
    {
        "name": "פוראקה",
        "enName": "Purake",
        "isNew": true,
        "rating": "(2) 4.5",
        "deal": "",
        "marketer": "קנדוק",
        "manufacturer": "קוטניי קולטיבר",
        "brand": "טוטם",
        "expiry": "02/27",
        "price": "₪499",
        "catalogPrice": "₪499",
        "parent1": "פוג'יווארה",
        "parent2": "קאפ ג'אנקי",
        "originStrain": "פוגו",
        "countryOfOrigin": "קנדה",
        "terpenes": "",
        "packageType": "שקית"
    }
]