export

    const mockData = [
        {
            "name": "גר.ליקס מיני",
            "enName": "Gar.Lix Mini",
            "isNew": false,
            "rating": "(0)3",
            "deal": "3 ב-₪279",
            "marketer": "טוגדר",
            "manufacturer": "קנאדו",
            "brand": "קנאדו",
            "expiry": "09/26",
            "price": "₪99",
            "catalogPrice": "₪299",
            "parent1": "גרליק ברת' 2.0",
            "parent2": "דיזיינר ראנטז",
            "originStrain": "גלייזד גרליק",
            "countryOfOrigin": "ישראל",
            "terpenes": "לא ידוע",
            "packageType": "שקית"
        },
        {
            "name": "ראיין",
            "enName": "Rhine",
            "isNew": true,
            "rating": "(0)3",
            "deal": "3 ב-₪279",
            "marketer": "קנטק",
            "manufacturer": "קנאפארמה",
            "brand": "לומה",
            "expiry": "12/26",
            "price": "₪99",
            "catalogPrice": "₪199",
            "parent1": "סקאנק #1",
            "parent2": "אפגני",
            "originStrain": "אוג'י צ'יז",
            "countryOfOrigin": "קנדה",
            "terpenes": "לא ידוע",
            "packageType": "שקית"
        },
        {
            "name": "ואנקה",
            "enName": "Wanaka",
            "isNew": false,
            "rating": "(9)3",
            "deal": "3 ב-₪299",
            "marketer": "קנפוקס",
            "manufacturer": "קנערבה",
            "brand": "טא-מוקו",
            "expiry": "11/27",
            "price": "₪109",
            "catalogPrice": "₪199",
            "parent1": "פלורידה אוג'י",
            "parent2": "אפגני",
            "originStrain": "ספאייר אוג'י",
            "countryOfOrigin": "ישראל",
            "terpenes": "לא ידוע",
            "packageType": "צנצנת"
        },
        {
            "name": "ראנגי",
            "enName": "Rangi",
            "isNew": false,
            "rating": "(1)3",
            "deal": "3 ב-₪299",
            "marketer": "קנפוקס",
            "manufacturer": "קנערבה",
            "brand": "טא-מוקו",
            "expiry": "11/27",
            "price": "₪109",
            "catalogPrice": "₪199",
            "parent1": "סטארדוג גויאבה",
            "parent2": "אוג'י קוש",
            "originStrain": "",
            "countryOfOrigin": "ישראל",
            "terpenes": "לא ידוע",
            "packageType": "צנצנת"
        },
        {
            "name": "אור ג'י.בי סמול",
            "enName": "Or G.B Small",
            "isNew": false,
            "rating": "(2)",
            "deal": "",
            "marketer": "טוגדר",
            "manufacturer": "לא ידוע",
            "brand": "טוגדר",
            "expiry": "01/27",
            "price": "₪129",
            "catalogPrice": "₪199",
            "parent1": "גלוברי",
            "parent2": "אוג'י קוש",
            "originStrain": "גלוברי או ג'י",
            "countryOfOrigin": "ישראל",
            "terpenes": "לא ידוע",
            "packageType": "שקית"
        },
        {
            "name": "אר.אס.סי",
            "enName": "R.S.C",
            "isNew": false,
            "rating": "(1)",
            "deal": "",
            "marketer": "טוגדר",
            "manufacturer": "קנאדו",
            "brand": "קנאדו",
            "expiry": "12/26",
            "price": "₪129",
            "catalogPrice": "₪399",
            "parent1": "ריינבו שרבט",
            "parent2": "קאפ ג'אנקי",
            "originStrain": "",
            "countryOfOrigin": "ישראל",
            "terpenes": "לא ידוע",
            "packageType": "שקית"
        },
        {
            "name": "גר.ליקס",
            "enName": "Gar.Lix",
            "isNew": false,
            "rating": "(1)",
            "deal": "",
            "marketer": "טוגדר",
            "manufacturer": "קנאדו",
            "brand": "קנאדו",
            "expiry": "07/26",
            "price": "₪129",
            "catalogPrice": "₪349",
            "parent1": "גרליק ברת' 2.0",
            "parent2": "דיזיינר ראנטז",
            "originStrain": "גלייזד גרליק",
            "countryOfOrigin": "ישראל",
            "terpenes": "לא ידוע",
            "packageType": "שקית"
        },
        {
            "name": "סלאק מיני",
            "enName": "Slac Mini",
            "isNew": true,
            "rating": "(0)",
            "deal": "",
            "marketer": "טוגדר",
            "manufacturer": "לא ידוע",
            "brand": "טוגדר",
            "expiry": "03/27",
            "price": "₪129",
            "catalogPrice": "₪329",
            "parent1": "אוג'י קוש ברת'",
            "parent2": "גויאבה ג'לאטו",
            "originStrain": "קריביאן קוקיז",
            "countryOfOrigin": "ישראל",
            "terpenes": "לינאלול, קריופילן, מירצן, לימונן, פיינן",
            "packageType": "שקית"
        },
        {
            "name": "דאבליו.אם.זד סמול",
            "enName": "W.M.Z Small",
            "isNew": true,
            "rating": "(2)",
            "deal": "",
            "marketer": "טוגדר",
            "manufacturer": "אוונט",
            "brand": "אוונט",
            "expiry": "12/26",
            "price": "₪135",
            "catalogPrice": "₪269",
            "parent1": "ווטרמלון",
            "parent2": "סקיטלז",
            "originStrain": "ווטרמלון סקיטלז",
            "countryOfOrigin": "קנדה",
            "terpenes": "יומולן, קריופילן, מירצן, פיינן, לימונן",
            "packageType": "שקית"
        },
        {
            "name": "אור ג'י.בי",
            "enName": "Or G.B",
            "isNew": false,
            "rating": "(2)",
            "deal": "",
            "marketer": "טוגדר",
            "manufacturer": "לא ידוע",
            "brand": "טוגדר",
            "expiry": "01/27",
            "price": "₪149",
            "catalogPrice": "₪329",
            "parent1": "גלוברי",
            "parent2": "אוג'י קוש",
            "originStrain": "גלוברי או ג'י",
            "countryOfOrigin": "ישראל",
            "terpenes": "לא ידוע",
            "packageType": "שקית"
        },
        {
            "name": "איי.וי.ג'י-אס",
            "enName": "A.V.G-S",
            "isNew": false,
            "rating": "(2)",
            "deal": "",
            "marketer": "טוגדר",
            "manufacturer": "אוונט",
            "brand": "אוונט",
            "expiry": "11/26",
            "price": "₪149",
            "catalogPrice": "₪349",
            "parent1": "סקיטלז",
            "parent2": "אפלז אנד בננז",
            "originStrain": "אייוי גז",
            "countryOfOrigin": "קנדה",
            "terpenes": "לא ידוע",
            "packageType": "שקית"
        },
        {
            "name": "סלאק",
            "enName": "Slac",
            "isNew": false,
            "rating": "(3)",
            "deal": "",
            "marketer": "טוגדר",
            "manufacturer": "לא ידוע",
            "brand": "טוגדר",
            "expiry": "02/27",
            "price": "₪149",
            "catalogPrice": "₪399",
            "parent1": "אוג'י קוש ברת'",
            "parent2": "גויאבה ג'לאטו",
            "originStrain": "קריביאן קוקיז",
            "countryOfOrigin": "ישראל",
            "terpenes": "לינאלול, קריופילן, מירצן, לימונן, פיינן",
            "packageType": "שקית"
        },
        {
            "name": "פלורו",
            "enName": "Floro",
            "isNew": true,
            "rating": "(1)",
            "deal": "",
            "marketer": "טוגדר",
            "manufacturer": "לא ידוע",
            "brand": "טוגדר",
            "expiry": "04/27",
            "price": "₪149",
            "catalogPrice": "₪219",
            "parent1": "בננה אוג'י קוש",
            "parent2": "סורבה",
            "originStrain": "בננה סורבה",
            "countryOfOrigin": "קנדה",
            "terpenes": "מירצן, לימונן, קריופילן",
            "packageType": "שקית"
        },
        {
            "name": "דון-בי",
            "enName": "Don-B",
            "isNew": false,
            "rating": "(2)3",
            "deal": "3 ב-₪449",
            "marketer": "שיח",
            "manufacturer": "לא ידוע",
            "brand": "שיח",
            "expiry": "02/27",
            "price": "₪159",
            "catalogPrice": "₪229",
            "parent1": "גריז מאנקי",
            "parent2": "טריפל אוג'י",
            "originStrain": "דונקי באטר",
            "countryOfOrigin": "קנדה",
            "terpenes": "לימונן 26%, קריופילן 24%, פיינן 15%, לינאלול 11%, יומולן 8%, אחרים 16%",
            "packageType": "שקית"
        },
        {
            "name": "לאסק",
            "enName": "Lask",
            "isNew": false,
            "rating": "(2)3",
            "deal": "3 ב-₪449",
            "marketer": "שיח",
            "manufacturer": "לא ידוע",
            "brand": "שיח",
            "expiry": "11/26",
            "price": "₪159",
            "catalogPrice": "₪229",
            "parent1": "קרים",
            "parent2": "אל.איי קוש קייק",
            "originStrain": "קרים קייק",
            "countryOfOrigin": "קנדה",
            "terpenes": "קריופילן 35%, פרנסן 18%, מירצן 13%, לימונן 9%, יומולן 8%, לינאלול 7%, ביסבולול 4%, אחרים 6%",
            "packageType": "שקית"
        },
        {
            "name": "אסטרו אף.סי.די",
            "enName": "Astro F.C.D",
            "isNew": true,
            "rating": "(4)",
            "deal": "",
            "marketer": "טוגדר",
            "manufacturer": "סיקסטי סבן סינס",
            "brand": "אסטרו",
            "expiry": "03/27",
            "price": "₪169",
            "catalogPrice": "₪199",
            "parent1": "איי קנדי",
            "parent2": "אפלז אנד בננז",
            "originStrain": "פאסאד",
            "countryOfOrigin": "קנדה",
            "terpenes": "לא ידוע",
            "packageType": "שקית"
        },
        {
            "name": "ג'י.אר.אל.זי",
            "enName": "G.R.L.Z",
            "isNew": false,
            "rating": "(4)",
            "deal": "",
            "marketer": "טוגדר",
            "manufacturer": "סי3",
            "brand": "טוגדר",
            "expiry": "02/27",
            "price": "₪169",
            "catalogPrice": "₪209",
            "parent1": "ג'י אם או",
            "parent2": "סקיטלז",
            "originStrain": "גרליק סקיטלז",
            "countryOfOrigin": "קנדה",
            "terpenes": "לא ידוע",
            "packageType": "שקית"
        },
        {
            "name": "ג'י.פי.טי סמול",
            "enName": "G.P.T Small",
            "isNew": false,
            "rating": "(4)",
            "deal": "",
            "marketer": "טוגדר",
            "manufacturer": "סי3",
            "brand": "טוגדר",
            "expiry": "02/27",
            "price": "₪169",
            "catalogPrice": "₪269",
            "parent1": "סטרוברי בננה",
            "parent2": "פרויו",
            "originStrain": "סטרוברי פרויו",
            "countryOfOrigin": "קנדה",
            "terpenes": "מירצן 33%, פיינן 28%, אוסימן 16%, אחרים 23%",
            "packageType": "שקית"
        },
        {
            "name": "קאטה",
            "enName": "Kata",
            "isNew": true,
            "rating": "(1)",
            "deal": "",
            "marketer": "",
            "manufacturer": "לא ידוע",
            "brand": "טוגדר",
            "expiry": "01/27",
            "price": "₪169",
            "catalogPrice": "₪199",
            "parent1": "",
            "parent2": "",
            "originStrain": "",
            "countryOfOrigin": "ישראל",
            "terpenes": "",
            "packageType": ""
        },
        {
            "name": "בי.סי.אר",
            "enName": "B.C.R",
            "isNew": false,
            "rating": "(3)",
            "deal": "",
            "marketer": "טוגדר",
            "manufacturer": "דיקאר",
            "brand": "ג'יי אר סטריין",
            "expiry": "11/26",
            "price": "₪175",
            "catalogPrice": "₪349",
            "parent1": "בננה אוג'י קוש",
            "parent2": "קוקיז אנד קרים",
            "originStrain": "בננה קרים",
            "countryOfOrigin": "קנדה",
            "terpenes": "לינאלול, מירצן, פיינן",
            "packageType": ""
        },
        {
            "name": "רוקס אם פי מיני",
            "enName": "Rox MP Mini",
            "isNew": true,
            "rating": "(0)",
            "deal": "",
            "marketer": "טוגדר",
            "manufacturer": "רוקסטון",
            "brand": "רוקסטון",
            "expiry": "04/27",
            "price": "₪175",
            "catalogPrice": "₪349",
            "parent1": "פנקייקס",
            "parent2": "מקפלרי",
            "originStrain": "פלאפ ג'קס",
            "countryOfOrigin": "קנדה",
            "terpenes": "פרנסן, לינאלול, קריופילן, לימונן, מירצן",
            "packageType": "שקית"
        },
        {
            "name": "אורזקי מיני",
            "enName": "Orzki Mini",
            "isNew": false,
            "rating": "(1)3",
            "deal": "3 ב-₪525",
            "marketer": "שיח",
            "manufacturer": "לא ידוע",
            "brand": "שיח",
            "expiry": "10/26",
            "price": "₪179",
            "catalogPrice": "₪269",
            "parent1": "אנימל מינטס",
            "parent2": "אורנג' סקיטלז",
            "originStrain": "מנגו מינט",
            "countryOfOrigin": "קנדה",
            "terpenes": "לימונן 24%, קריופילן 17%, לינאלול 11%, פנצ'ול 7%, פרנסן 6%, טרפינאול 5.5%, יומולן 5.5%, מירצן 5%, אחרים 19%",
            "packageType": "שקית"
        },
        {
            "name": "ג'י.פי.איי.אי מיני",
            "enName": "G.P.I.E Mini",
            "isNew": true,
            "rating": "(2)",
            "deal": "",
            "marketer": "טוגדר",
            "manufacturer": "לא ידוע",
            "brand": "טוגדר",
            "expiry": "02/27",
            "price": "₪179",
            "catalogPrice": "₪329",
            "parent1": "ג'לאטי",
            "parent2": "קוש מינטס",
            "originStrain": "ג'ורג'יה פאי",
            "countryOfOrigin": "קנדה",
            "terpenes": "לינאלול, קריופילן, מירצן, לימונן, פיינן",
            "packageType": "שקית"
        },
        {
            "name": "פרפל דידי מיני",
            "enName": "Purple DD Mini",
            "isNew": false,
            "rating": "(1)3",
            "deal": "3 ב-₪525",
            "marketer": "שיח",
            "manufacturer": "לא ידוע",
            "brand": "שיח",
            "expiry": "11/26",
            "price": "₪179",
            "catalogPrice": "₪279",
            "parent1": "גרנדדי פרפל",
            "parent2": "בננה דדי",
            "originStrain": "",
            "countryOfOrigin": "קנדה",
            "terpenes": "מירצן 40%, קריופילן 17%, אוסימן 13.5%, פיינן 12%, יומולן 5%, ביסבולול 2%, אחרים 10.5%",
            "packageType": "שקית"
        },
        {
            "name": "טיימס",
            "enName": "Thames",
            "isNew": true,
            "rating": "(0)3",
            "deal": "3 ב-₪525",
            "marketer": "קנטק",
            "manufacturer": "לא ידוע",
            "brand": "קנאוורו",
            "expiry": "12/26",
            "price": "₪189",
            "catalogPrice": "₪249",
            "parent1": "אוראוז",
            "parent2": "סופר בוף",
            "originStrain": "סאב זירו",
            "countryOfOrigin": "ישראל",
            "terpenes": "לא ידוע",
            "packageType": "שקית"
        }
    ]